/* eslint-disable */
/* global WebImporter */
/**
 * Parser for accordion-picker. Base: accordion. Source: http://localhost:8765/reports/
 * Selector: .builder .col-group
 *
 * The selector matches EACH .col-group, but all groups belong to ONE block. On the first
 * match the parser collects the contiguous run of sibling .col-group elements, builds a
 * single block (one row per group) and removes the other groups; later matches are already
 * detached and are skipped. If handed a container instead, it uses its .col-group descendants.
 *
 * Output (accordion convention: 2 columns, title | content; xwalk item model
 * accordion-picker-item):
 *   [ <!-- field:title --> h3 text | <!-- field:options --> <ul><li>label</li>...</ul> ]
 *
 * Dropped (regenerated by the block): .col-head search input / "Search" text, clear and
 * move-up icon links (:clear: / :move-up: after gatx-cleanup), and the p.select-all
 * "Select All / Unselect All" links.
 * Works on the raw DOM (label > input[type=checkbox] + text) and after gatx-cleanup
 * (checkbox removed, label text kept). Iteration keyed on div.col-group (block-level
 * wrapper, no nested interactive elements).
 */
const ITEM_SELECTOR = '.col-group';

const clean = (s) => (s || '').replace(/\s+/g, ' ').trim();

function collectGroups(element) {
  if (!element.matches(ITEM_SELECTOR)) {
    return [...element.querySelectorAll(ITEM_SELECTOR)];
  }
  let first = element;
  while (first.previousElementSibling && first.previousElementSibling.matches(ITEM_SELECTOR)) {
    first = first.previousElementSibling;
  }
  const groups = [];
  let cur = first;
  while (cur && cur.matches(ITEM_SELECTOR)) {
    groups.push(cur);
    cur = cur.nextElementSibling;
  }
  return groups;
}

function hinted(document, fieldName, node) {
  if (!node) return '';
  const frag = document.createDocumentFragment();
  frag.appendChild(document.createComment(` field:${fieldName} `));
  frag.appendChild(typeof node === 'string' ? document.createTextNode(node) : node);
  return frag;
}

function labelText(label) {
  const copy = label.cloneNode(true);
  copy.querySelectorAll('input, select, button, textarea').forEach((c) => c.remove());
  return clean(copy.textContent);
}

function groupOptions(group) {
  // Option labels only - skip header controls and the select-all links.
  const isControl = (el) => el.closest('.col-head, .select-all');
  let texts = [...group.querySelectorAll('label')].filter((l) => !isControl(l)).map(labelText);
  if (!texts.length) {
    texts = [...group.querySelectorAll('li')].filter((li) => !isControl(li))
      .map((li) => clean(li.textContent));
  }
  return texts.filter(Boolean);
}

function buildList(document, items) {
  if (!items.length) return null;
  const ul = document.createElement('ul');
  items.forEach((text) => {
    const li = document.createElement('li');
    li.textContent = text;
    ul.append(li);
  });
  return ul;
}

export default function parse(element, { document }) {
  const groups = collectGroups(element);
  if (!groups.length) return;

  const cells = groups.map((group) => {
    const heading = group.querySelector('.col-head h3, h3, h4, h2, legend');
    const title = heading ? clean(heading.textContent) : '';
    return [
      hinted(document, 'title', title || null),
      hinted(document, 'options', buildList(document, groupOptions(group))),
    ];
  });

  const block = WebImporter.Blocks.createBlock(document, { name: 'accordion-picker', cells });

  if (element.matches(ITEM_SELECTOR)) {
    const first = groups[0];
    groups.slice(1).forEach((g) => g.remove());
    if (element !== first) {
      first.replaceWith(block);
      if (element.parentNode) element.remove();
    } else {
      element.replaceWith(block);
    }
  } else {
    element.replaceWith(block);
  }
}
